package com.tntmodders.scp_040_jp.core;

import com.tntmodders.scp_040_jp.SCP040JPCore;
import net.minecraftforge.fml.common.ModMetadata;

public class SCP040JPModInfo {

    public static void load(ModMetadata meta) {
        meta.modId = SCP040JPCore.MODID;
        meta.name = "ねこのMODです。";
        meta.description = "このMODは http://www.scp-wiki.net/ の内容をもとに独自に二次創作した内容です。";
        meta.version = SCP040JPCore.VERSION;
        meta.credits = "'Ikr_4185' 氏作 「SCP-040-JP」( http://ja.scp-wiki.net/scp-040-jp )に基づき、CC BY-SA " +
                "3.0の下でこのMODを公開しています。";
        meta.url = "https://www.tntmodders.com";
        meta.authorList.add("Tom kate");
        meta.autogenerated = false;
    }
}